<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>1.1.1</Version>
        <ModVersion>$(Version)</ModVersion>
        <ZipName>zero_loss_coke</ZipName>
    </PropertyGroup>

    <PropertyGroup>
        <TargetFrameworks>net7.0;net8.0</TargetFrameworks>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>

        <OutputPath>artifacts/$(Configuration)/Mods/$(TargetFramework)/</OutputPath>
        <ReleaseDir>$(ProjectDir)Releases</ReleaseDir>
    </PropertyGroup>

    <PropertyGroup>
        <Deterministic>true</Deterministic>
        <ImplicitUsings>false</ImplicitUsings>
        <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <DebugType>none</DebugType>
        <DebugSymbols>false</DebugSymbols>
        <GenerateDependencyFile>false</GenerateDependencyFile>
    </PropertyGroup>

    <PropertyGroup Condition="'$(TargetFramework)' == 'net7.0'">
        <DefineConstants>NET7_0</DefineConstants>
        <VsLibPath>libs/vintagestory/net7.0</VsLibPath>
    </PropertyGroup>

    <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0'">
        <DefineConstants>NET8_0</DefineConstants>
        <VsLibPath>libs/vintagestory/net8.0</VsLibPath>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="VintagestoryAPI">
            <HintPath>$(VsLibPath)/VintagestoryAPI.dll</HintPath>
            <Private>false</Private>
        </Reference>

        <Reference Include="0Harmony">
            <HintPath>$(VsLibPath)/0Harmony.dll</HintPath>
            <Private>false</Private>
        </Reference>

        <Reference Include="VSSurvivalMod">
            <HintPath>$(VsLibPath)/VSSurvivalMod.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <Content Include="modinfo.json" CopyToOutputDirectory="PreserveNewest"/>
        <Content Include="modicon.png" Condition="Exists('modicon.png')" CopyToOutputDirectory="PreserveNewest"/>
        <Content Include="README.md" Condition="Exists('README.md')" CopyToOutputDirectory="PreserveNewest"/>
        <Content Include="LICENSE" Condition="Exists('LICENSE')" CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>

    <Target Name="ZipMod" AfterTargets="Build" Condition="'$(Configuration)' == 'Release' And Exists('$(OutputPath)$(AssemblyName).dll')">
        <MakeDir Directories="$(ReleaseDir)"/>

        <PropertyGroup>
            <ZipFile>$(ReleaseDir)/$(ZipName)_v$(ModVersion)_$(TargetFramework).zip</ZipFile>
        </PropertyGroup>

        <Message Text="Zipping $(OutputPath) -> $(ZipFile)" Importance="High"/>

        <ZipDirectory SourceDirectory="$(OutputPath)" DestinationFile="$(ZipFile)" Overwrite="true"/>
    </Target>

</Project>